<a id="1"></a>
<div style="padding:20px;
            color:#F0F3FF;
            margin:10;
            font-size:200%;
            text-align:left;
            display:fill;
            border-radius:15px;
            background-color:#211951;
            overflow:hidden;
            font-weight:900">
            <span style='color:#15F5BA'></span>Pandas : Data Manipulation
</div>

# <b>A. <span style='color:#3A6D8C'>Introduction</span></b>

Sebelum sebuah data dapat dianalisis atau digunakan untuk mengambil keputusan kebijakan tentu data tersebut perlu untuk diekstraksi terlebih dahulu. <b>Ekstraksi data</b> adalah sebuah proses pengumpulan atau pengambilan jenis data yang berbeda dari berbagai sumber, banyak di antaranya mungkin tidak terorganisir dengan baik atau tidak terstruktur sama sekali. Proses ini memungkinkan untuk mengkonsolidasikan, memproses, dan menyempurnakan data sehingga nantinya dapat disimpan di lokasi terpusat untuk diubah atau diproses lebih lanjut.

Python sebagai salah satu <i>tools</i> yang <i>powerful</i> untuk pengolahan data menyediakan berbagai <i>library</i> untuk mendukung proses ekstraksi data. Salah satu library paling banyak digunakan adalah <b>pandas</b>.

Pandas memungkinkan untuk membaca data dari berbagai jenis ekstensi seperti data yang bersumber dari database (sql), <i>excel</i> (<b>.xls</b> atau <b>.xlsx</b>), <i>separated value file</i> (<b>.csv</b>, <b>.tsv</b>, dsb) lalu merubahnya menjadi satu format struktur data yang sama yang disebut <b>DataFrame</b>. DataFrame inilah yang nantinya dapat kita lakukan proses <b>Data Manipulation</b><br><br>

<p align="center">
<img src="https://raw.githubusercontent.com/bachtiyarma/Material/refs/heads/main/Image/Materi-Python/Pandas-DataFrame.png" width="600" height="300">
<p align="center"><b>Gambar 1. Proses Ekstraksi Data dengan <i>pandas</i></b></p>
<br><br>
<p align="left"><sup>docs : <i><a href="https://shorturl.at/xyZ69">https://pandas.pydata.org/docs/user_guide/io.html</i></sup></a></p>

## <b>A.1. <span style='color:#6A9AB0'>First Step : Pandas</span></b>  
Untuk dapat menggunakan library pandas pada python, perlu untuk mengimpor library tersebut dengan cara mengetikan sintaks berikut

<p align="center"><code><b>import pandas as pd</b></code></p>

lalu jalankan (<i>run</i>) program.
<br><br>
<p align="left"><sup>docs : <i><a href="https://shorturl.at/kzG06">https://pandas.pydata.org/docs/getting_started/install.html</i></sup></a></p>

###<b><span style='color:#55679C'>Quest A.1</span></b>
<i>Ketikan kode `import pandas as pd` pada prompt dibawah ini lalu jalankan!</i>

In [1]:
# Answer A.1
import pandas as pd

# <b>B. <span style='color:#3A6D8C'>Struktur Data Pandas</span></b>

* Terdapat dua struktur data utama pada library pandas yang disebut dengan Series dan DataFrame.
<p align="center">
<img src="https://datagy.io/wp-content/uploads/2022/12/Understanding-Pandas-Series-and-DataFrames-1024x576.png" width="550" height="289">
<p align="center"><b>Gambar 2. Series VS DataFrame</b></p>
<br>

* Gabungan beberapa Series yang mempunyai banyak baris yang sama dapat membentuk sebuah DataFrame atau berlaku sebaliknya pada sebuah DataFrame dapat dipecah (di-<i>slicing</i> satu kolom) membentuk sebuah Series.<br><br>

<ul><p align="left"><sup>docs : <i><a href="https://shorturl.at/dezQY">http://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html</i></sup></a></p></ul>

## <b>B.1. <span style='color:#6A9AB0'>Series</span></b>  

* <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html">Series</a> merupakan kolom dari sebuah tabel yang bersifat homogen atau mempunyai elemen dengan tipe data yang sejenis.

* Untuk membuat Series gunakan sintaks berikut

<p align="center"><code><b>pd.Series(data)</b></code></p>

<ul>
  data dapat berupa <i>array-like</i>, <i>Iterable</i>, <i>dict</i>, atau <i>scalar</i>
</ul>
<br>
<ul><p align="left"><sup>docs : <i><a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html">https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html</i></sup></a></p></ul>

###<b><span style='color:#55679C'>Quest B.1.1</span></b>
<i>Hanya Singapura dan Indonesia yang saat ini telah menetapkan pajak karbon (carbon pricing) di Asia Tenggara. (source : https://accept.aseanenergy.org/progress-of-carbon-pricing-in-asean)

Buatlah sebuah Series yang disimpan pada variabel dengan nama `country_carbon_pricing` untuk menampung nama negara yang telah menetapkan pajak karbon di Asia Tenggara, lalu tampilkan outputnya!</i>

In [3]:
# Answer B.1.1
country_carbon_pricing = pd.Series(['Singapore', 'Indonesia'])
print(country_carbon_pricing)

0    Singapore
1    Indonesia
dtype: object

###<b><span style='color:#55679C'>Quest B.1.2</span></b>
<i>Dari data emisi karbon yang tercatat di Indonesia, akan diberi detail data sebagai berikut

* Tahun 2015 dihasilkan 491.46 Mton CO2
* Tahun 2016 dihasilkan 488.40 Mton CO2
* Tahun 2017 dihasilkan 511.33 Mton CO2
* Tahun 2018 dihasilkan 579.23 Mton CO2
* Tahun 2019 dihasilkan 625.66 Mton CO2

<i>Source: Joint Research Centre of European Union</i>

Dari data tersebut buatlah sebuah Series yang disimpan pada variabel dengan nama `emisi_co2_indonesia` lalu tampilkan outputnya!</i>

In [4]:
# Answer B.1.2
emisi_co2_indonesia = pd.Series([491.46, 488.40, 511.33, 579.23, 625.66 ],
                                index=['Tahun 2015', 'Tahun 2016', 'Tahun 2017', 'Tahun 2018', 'Tahun 2019'])
print(emisi_co2_indonesia)

Tahun 2015    491.46
Tahun 2016    488.40
Tahun 2017    511.33
Tahun 2018    579.23
Tahun 2019    625.66
dtype: float64

## <b>B.2. <span style='color:#6A9AB0'>DataFrame</span></b>  

* <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame">DataFrame</a> adalah struktur data 2 dimensi yang terdiri dari baris dan kolom (seperti tabel) dan dapat menyimpan data dari berbagai jenis (termasuk karakter, bilangan bulat, bilangan real, data kategorikal, dan lainnya).

<p align="center">
<img src="https://www.w3resource.com/w3r_images/pandas-data-frame.svg" width="600" height="300">
<p align="center"><b>Gambar 2. DataFrame Pandas</b></p>
<br>

* <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series">Series</a> merupakan kolom dari sebuah tabel yang bersifat homogen atau mempunyai elemen dengan tipe data yang sejenis.


<p align="center">
<img src="https://datagy.io/wp-content/uploads/2022/12/Understanding-Pandas-Series-and-DataFrames-1024x576.png" width="550" height="300">
<p align="center"><b>Gambar 3. Series VS DataFrame</b></p>
<br>

* Gabungan beberapa Series yang mempunyai banyak baris yang sama dapat membentuk sebuah DataFrame atau berlaku sebaliknya pada sebuah DataFrame dapat dipecah (di-<i>slicing</i> satu kolom) membentuk sebuah Series.<br><br>

* Untuk membuat sebuah DataFrame secara manual, dapat menggunakan sintaks
<p align="center"><code><b>pd.DataFrame(data)</b></code></p>
<ul>data inputan dapat berupa ndarray (structured atau homogeneous), iterable atau dict</ul>
<br>
<ul><p align="left"><sup>docs : <i><a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html">https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html</i></sup></a></p></ul>

###<b><span style='color:#55679C'>Quest B.2</span></b>
<i>Diberikan data Air Quality Index (AQI) dan partikel udara yang memiliki diameter kurang dari 2,5 mikrometer (PM2.5) di Jakarta (source : <a href="https://www.iqair.com/id/indonesia/jakarta?srsltid=AfmBOoqcwssGzLEzHMeGJwjaU-oi7wh1JeUqR-wBxicstXuvUN_i5UwT">https://www.iqair.com/id/indonesia/jakarta?srsltid=AfmBOoqcwssGzLEzHMeGJwjaU-oi7wh1JeUqR-wBxicstXuvUN_i5UwT</a>) sebagai berikut :</i>
<br><br>
<table>
    <tr>
        <th>Tanggal</th>
        <th>PM2.5</th>
        <th>AQI</th>
    </tr>
    <tr>
        <td>2024-09-21</td>
        <td>70.7</td>
        <td>162</td>
    </tr>
    <tr>
        <td>2024-09-22</td>
        <td>58.6</td>
        <td>153</td>
    </tr>
    <tr>
        <td>2024-09-23</td>
        <td>52.3</td>
        <td>142</td>
    </tr>
</table>
<br>

<i>Dari data diatas, buatkan secara manual DataFrame-nya dengan pandas!</i>

In [10]:
# Answer B.2
data = pd.DataFrame({'tanggal': ['2024-09-21', '2024-09-22', '2024-09-23'],
                          'pm2.5': [70.7, 58.6, 52.3],
                          'aqi': [162, 153, 142]})
display(data)

      tanggal  pm2.5  aqi
0  2024-09-21   70.7  162
1  2024-09-22   58.6  153
2  2024-09-23   52.3  142

## <b>B.3. <span style='color:#6A9AB0'>Parts Of DataFrame</span></b>

Untuk lebih memahami objek DataFrame, perlu diketahui bahwa DataFrame terdiri dari tiga komponen sebagai atribut berikut :

<ul>1️⃣ .values : Nilai - nilai yang tertera pada DataFrame</ul>
<ul>2️⃣ .columns : Nama kolom yang ada pada DataFrame</ul>
<ul>3️⃣ .index : Nama atau nomor index pada DataFrame</ul>

###<b><span style='color:#55679C'>Quest B.3.1</span></b>

<i>Pada DataFrame yang telah dibuat pada Quest B.2, coba buatkan list nama kolomnya!</i>

In [11]:
# Answer B.3.1
data.columns

Index(['tanggal', 'pm2.5', 'aqi'], dtype='object')

###<b><span style='color:#55679C'>Quest B.3.2</span></b>

<i>Pada DataFrame yang telah dibuat pada Quest B.2, coba akses setiap nilainya!</i>

In [12]:
# Answer B.3.2
data.values

array([['2024-09-21', 70.7, 162],
       ['2024-09-22', 58.6, 153],
       ['2024-09-23', 52.3, 142]], dtype=object)

# <b>C. <span style='color:#3A6D8C'>Data Manipulation</span></b>

Data Manipulation adalah sebuah metode pengorganisasian data agar lebih mudah dibaca, terstruktur dan agar lebih mudah diolah untuk kebutuhan lain kedepannya. Beberapa hal yang biasa dilakukan saat data manipulation adalah sebagai berikut :


<ul>1️⃣ Column selections</ul>
<ul>2️⃣ Filter the data</ul>
<ul>3️⃣ Create a new column or change it</ul>
<ul>4️⃣ Drop a column</ul>
<ul>5️⃣ Apply custom functions</ul>
<ul>6️⃣ Join / Merge the data</ul>
<ul>7️⃣ etc</ul>

## <b>C.1. <span style='color:#6A9AB0'>Data Extraction</span></b>

* Dalam konteks data extraction, Pandas dapat digunakan untuk membaca data dari berbagai sumber, seperti file CSV, Excel, SQL database, dan lainnya, dan mengubahnya menjadi DataFrames untuk analisis lebih lanjut.

* Beberapa fungsi dan metode Pandas yang umum digunakan untuk data extraction adalah sebagai berikut:

<ul>
<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html">pd.read_csv()</a></code>: Digunakan untuk membaca data dari file CSV dan mengonversinya menjadi DataFrame.

<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html">pd.read_excel()</a></code>: Membaca data dari file Excel dan membuat DataFrame dari lembar kerja atau tabel tertentu.

<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html">pd.read_sql()</a></code>: Mengambil data dari basis data SQL menggunakan SQL query dan menyimpannya dalam bentuk DataFrame.
</ul>

###<b><span style='color:#55679C'>Quest C.1.</span></b>

<i>Untuk melakukan proses ekstraksi data, lakukan instruksi berikut :     

1.   Persiapkan dataset WorldSustainabilityDataset.csv
2.   Upload ke google colab dengan cara pilih File pada bagian kiri laman (icon 📁), kemudian klik kanan dan pilih upload
3.   Lakukan ekstraksi data csv (.csv) dengan library pandas, assign hasilnya ke sebuah variabel bernama <code>data_world_sust</code>
4.   Tampilkan hasilnya</i>

In [14]:
# Answer C.1.
data_world_sust = pd.read_csv('WorldSustainabilityDataset.csv')

## <b>C.2. <span style='color:#6A9AB0'>Inspecting Data Information</span></b>

* Untuk dapat menginspeksi informasi umum pada data dapat menggunakan sintaks berikut

<p align="center"><code><b>DataFrame.info()</b></code></p>

<ul>Ketika dijalankan, sintaks tersebut akan menghasilkan output informasi umum pada data seperti banyak kolom, nama kolom beserta tipe data dan jumlah data tak kosong (<i>non-null value</i>)</ul><br>

<ul><p align="left"><sup>docs : <i><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html">https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html</i></sup></a></p></ul>

### <b><span style='color:#55679C'>Quest C.2</span></b>

<i>Inspeksi informasi umum pada data yang telah diekstraksi dan telah disimpan pada variabel <code>data_world_sust</code>. Setelah itu coba uraikan informasi apa yang bisa didapatkan setelah melakukan inspeksi informasi umum pada <code>data_world_sust</code>?</i>

In [15]:
# Answer C.2
data_world_sust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3287 entries, 0 to 3286
Data columns (total 54 columns):
 #   Column                                                                                        Non-Null Count  Dtype
---  ------                                                                                        --------------  -----
 0   Country Name                                                                                  3287 non-null   object
 1   Country Code                                                                                  3287 non-null   object
 2   Year                                                                                          3287 non-null   int64
 3   Access to electricity (% of population) - EG.ELC.ACCS.ZS                                      3193 non-null   float64
 4   Adjusted net national income per capita (annual % growth) - NY.ADJ.NNTY.PC.KD.ZG              2566 non-null   float64
 5   Adjusted net savings, excluding particulate emission damage (% of GNI) - NY.ADJ.SVNX.GN.ZS    2628 non-null   float64
 6   Adjusted savings: carbon dioxide damage (% of GNI) - NY.ADJ.DCO2.GN.ZS                        3220 non-null   float64
 7   Adjusted savings: natural resources depletion (% of GNI) - NY.ADJ.DRES.GN.ZS                  3094 non-null   float64
 8   Adjusted savings: net forest depletion (% of GNI) - NY.ADJ.DFOR.GN.ZS                         3111 non-null   float64
 9   Adjusted savings: particulate emission damage (% of GNI) - NY.ADJ.DPEM.GN.ZS                  3099 non-null   float64
 10  Automated teller machines (ATMs) (per 100,000 adults) - FB.ATM.TOTL.P5                        2285 non-null   float64
 11  Broad money (% of GDP) - FM.LBL.BMNY.GD.ZS                                                    2777 non-null   float64
 12  Children out of school (% of primary school age) - SE.PRM.UNER.ZS                             2225 non-null   float64
 13  Compulsory education, duration (years) - SE.COM.DURS                                          2979 non-null   float64
 14  Cost of business start-up procedures, female (% of GNI per capita) - IC.REG.COST.PC.FE.ZS     2501 non-null   float64
 15  Cost of business start-up procedures, male (% of GNI per capita) - IC.REG.COST.PC.MA.ZS       2501 non-null   float64
 16  Exports of goods and services (% of GDP) - NE.EXP.GNFS.ZS                                     3118 non-null   float64
 17  Final consumption expenditure (% of GDP) - NE.CON.TOTL.ZS                                     3047 non-null   float64
 18  GDP (current US$) - NY.GDP.MKTP.CD                                                            3246 non-null   float64
 19  GDP per capita (current US$) - NY.GDP.PCAP.CD                                                 3246 non-null   float64
 20  General government final consumption expenditure (% of GDP) - NE.CON.GOVT.ZS                  3031 non-null   float64
 21  Gross national expenditure (% of GDP) - NE.DAB.TOTL.ZS                                        3047 non-null   float64
 22  Gross savings (% of GDP) - NY.GNS.ICTR.ZS                                                     2774 non-null   float64
 23  Imports of goods and services (% of GDP) - NE.IMP.GNFS.ZS                                     3118 non-null   float64
 24  Inflation, consumer prices (annual %) - FP.CPI.TOTL.ZG                                        3083 non-null   float64
 25  Primary completion rate, total (% of relevant age group) - SE.PRM.CMPT.ZS                     2226 non-null   float64
 26  Proportion of seats held by women in national parliaments (%) - SG.GEN.PARL.ZS                3062 non-null   float64
 27  Pupil-teacher ratio, primary - SE.PRM.ENRL.TC.ZS                                              2366 non-null   float64
 28  Renewable electricity output (% of total electricity output) - EG.ELC.RNEW.ZS                 2771 non-null   float64
 29  Renewable energy consumption (% of total final energy consumption) - EG.FEC.RNEW.ZS           3287 non-null   float64
 30  School enrollment, preprimary (% gross) - SE.PRE.ENRR                                         2349 non-null   float64
 31  School enrollment, primary (% gross) - SE.PRM.ENRR                                            2783 non-null   float64
 32  School enrollment, secondary (% gross) - SE.SEC.ENRR                                          2430 non-null   float64
 33  Trade (% of GDP) - NE.TRD.GNFS.ZS                                                             3118 non-null   float64
 34  Women Business and the Law Index Score (scale 1-100) - SG.LAW.INDX                            3211 non-null   float64
 35  Prevalence of undernourishment (%) - SN_ITK_DEFC - 2.1.1                                      1834 non-null   float64
 36  Proportion of population below international poverty line (%) - SI_POV_DAY1 - 1.1.1           1304 non-null   float64
 37  Proportion of population covered by at least a 2G mobile network (%) - IT_MOB_2GNTWK - 9.c.1  2349 non-null   float64
 38  Proportion of population covered by at least a 3G mobile network (%) - IT_MOB_3GNTWK - 9.c.1  1357 non-null   float64
 39  Proportion of population using basic drinking water services (%) - SP_ACS_BSRVH2O - 1.4.1     1837 non-null   float64
 40  Unemployment rate, male (%) - SL_TLF_UEM - 8.5.2                                              1807 non-null   float64
 41  Unemployment rate, women (%) - SL_TLF_UEM - 8.5.2                                             1806 non-null   float64
 42  Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes         3285 non-null   float64
 43  Continent                                                                                     3285 non-null   object
 44  Gini index (World Bank estimate) - SI.POV.GINI                                                1303 non-null   float64
 45  Income Classification (World Bank Definition)                                                 3285 non-null   object
 46  Individuals using the Internet (% of population) - IT.NET.USER.ZS                             2986 non-null   float64
 47  Life expectancy at birth, total (years) - SP.DYN.LE00.IN                                      3096 non-null   float64
 48  Population, total - SP.POP.TOTL                                                               3106 non-null   float64
 49  Regime Type (RoW Measure Definition)                                                          3076 non-null   object
 50  Rural population (% of total population) - SP.RUR.TOTL.ZS                                     3278 non-null   float64
 51  Total natural resources rents (% of GDP) - NY.GDP.TOTL.RT.ZS                                  3053 non-null   float64
 52  Urban population (% of total population) - SP.URB.TOTL.IN.ZS                                  3106 non-null   float64
 53  World Regions (UN SDG Definition)                                                             3285 non-null   object
dtypes: float64(47), int64(1), object(6)
memory usage: 1.4+ MB

## <b>C.3. <span style='color:#6A9AB0'>Data Selection</span></b>

* Untuk memilih kolom tertentu pada sebuah DataFrame dapat menggunakan sintaks berikut

<p align="center"><code><b>DataFrame.loc[baris : nama_kolom]</b></code></p>

* <code>baris</code>
<ul>
  <li>Gunakan simbol ( : ) untuk menampilkan semua data</li>
  <li>Gunakan simbol (m : n) untuk menampilkan data dari index ke - m sampai dengan index ke - n</li>
</ul>

* <code>nama_kolom</code>
<ul>
  <li>Gunakan string untuk mengakses satu kolom saja (<i>return : Series</i>)</li>
  <li>Gunakan list untuk mengakses lebih dari satu kolom  (<i>return : DataFrame</i>)</li>
</ul>

###<b><span style='color:#55679C'>Quest C.3.1</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, simpan 18 data teratas ke dalam variabel **year** untuk kolom **Year** saja. Kemudian tampilkan data tersebut!</i>

In [16]:
# Answer C.3.1
year = data_world_sust.loc[:18, 'Year']
display(year)

0     2000
1     2001
2     2002
3     2003
4     2004
5     2005
6     2006
7     2007
8     2008
9     2009
10    2010
11    2011
12    2012
13    2013
14    2014
15    2015
16    2016
17    2017
18    2018
Name: Year, dtype: int64

###<b><span style='color:#55679C'>Quest C.3.2</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, Tampilkan 18 data teratas untuk kolom
* Country Name
* Year
* Access to electricity (% of population) - EG.ELC.ACCS.ZS</i>

In [17]:
# Answer C.3.2
data_world_sust[['Country Name', 'Year', 'Access to electricity (% of population) - EG.ELC.ACCS.ZS']].head(19)

,Country Name,Year,Access to electricity (% of population) - EG.ELC.ACCS.ZS
0,Aruba,2000,91.660398
1,Aruba,2001,100.000000
2,Aruba,2002,100.000000
3,Aruba,2003,100.000000
4,Aruba,2004,100.000000
5,Aruba,2005,100.000000
6,Aruba,2006,100.000000
7,Aruba,2007,100.000000
8,Aruba,2008,100.000000
9,Aruba,2009,100.000000
10,Aruba,2010,93.356292
11,Aruba,2011,100.000000
12,Aruba,2012,100.000000
13,Aruba,2013,100.000000
14,Aruba,2014,100.000000
15,Aruba,2015,100.000000
16,Aruba,2016,100.000000
17,Aruba,2017,100.000000
18,Aruba,2018,100.000000

## <b>C.4. <span style='color:#6A9AB0'>Conditions</span></b>

* Salah satu teknik paling sederhana untuk menemukan bagian mana dari kumpulan data yang menarik adalah menemukan subset baris yang cocok dengan beberapa kriteria untuk difilter atau dipilih. Untuk melakukan hal ini cukup mudah yakni dengan menuliskan kondisi seperti berikut

<p align="center"><code><b>DataFrame.loc[conditions]</b></code></p>

* Conditions dapat dibentuk dari 1 atau lebih kriteria boolean dan dihubungkan dengan operator logika and (&), or (|) atau not (~)

<br>

docs : <i>https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html</i>

###<b><span style='color:#55679C'>Quest C.4.1</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, tampilkan semua data yang Country Name-nya Indonesia</i>

In [18]:
# Answer C.4.1
data_Indonesia = data_world_sust.loc[data_world_sust['Country Name'] == 'Indonesia']
display(data_Indonesia)

,Country Name,Country Code,Year,Access to electricity (% of population) - EG.ELC.ACCS.ZS,Adjusted net national income per capita (annual % growth) - NY.ADJ.NNTY.PC.KD.ZG,"Adjusted net savings, excluding particulate emission damage (% of GNI) - NY.ADJ.SVNX.GN.ZS",Adjusted savings: carbon dioxide damage (% of GNI) - NY.ADJ.DCO2.GN.ZS,Adjusted savings: natural resources depletion (% of GNI) - NY.ADJ.DRES.GN.ZS,Adjusted savings: net forest depletion (% of GNI) - NY.ADJ.DFOR.GN.ZS,Adjusted savings: particulate emission damage (% of GNI) - NY.ADJ.DPEM.GN.ZS,...,Gini index (World Bank estimate) - SI.POV.GINI,Income Classification (World Bank Definition),Individuals using the Internet (% of population) - IT.NET.USER.ZS,"Life expectancy at birth, total (years) - SP.DYN.LE00.IN","Population, total - SP.POP.TOTL",Regime Type (RoW Measure Definition),Rural population (% of total population) - SP.RUR.TOTL.ZS,Total natural resources rents (% of GDP) - NY.GDP.TOTL.RT.ZS,Urban population (% of total population) - SP.URB.TOTL.IN.ZS,World Regions (UN SDG Definition)
1368,Indonesia,IDN,2000,86.300000,175.094481,13.605523,3.174163,7.519280,0.0,0.995095,...,28.6,Low income,NaN,NaN,NaN,Electoral Democracy,57.998,NaN,NaN,Eastern and South-Eastern Asia
1369,Indonesia,IDN,2001,86.260000,29.740863,1.569265,3.703188,5.594517,0.0,0.900631,...,29.0,Low income,2.018614,66.037,214427419.0,Electoral Democracy,57.217,8.147302,42.783,Eastern and South-Eastern Asia
1370,Indonesia,IDN,2002,87.600000,-128.869275,-1.002698,3.256460,4.368919,0.0,0.836755,...,31.7,Low income,2.134136,66.321,217357790.0,Electoral Democracy,56.432,6.475675,43.568,Eastern and South-Eastern Asia
1371,Indonesia,IDN,2003,87.940000,-446.094475,-2.707184,2.945079,4.143268,0.0,0.823148,...,31.9,Lower-middle income,2.387020,66.631,220309473.0,Electoral Democracy,55.644,6.354044,44.356,Eastern and South-Eastern Asia
1372,Indonesia,IDN,2004,89.010000,-88.418979,-3.832204,3.036238,5.428775,0.0,0.819240,...,32.7,Lower-middle income,2.600286,66.969,223285666.0,Electoral Democracy,54.851,8.366587,45.149,Eastern and South-Eastern Asia
1373,Indonesia,IDN,2005,85.421112,229.493078,-1.136493,2.921757,6.790490,0.0,0.798981,...,33.0,Lower-middle income,3.602025,67.334,226289468.0,Electoral Democracy,54.058,9.731952,45.942,Eastern and South-Eastern Asia
1374,Indonesia,IDN,2006,90.620000,-52.439762,1.621539,2.420132,6.223231,0.0,0.787130,...,34.3,Lower-middle income,4.764813,67.717,229318262.0,Electoral Democracy,53.262,9.291362,46.738,Eastern and South-Eastern Asia
1375,Indonesia,IDN,2007,91.100000,-645.655290,1.211209,2.328722,6.306531,0.0,0.776428,...,35.7,Lower-middle income,5.786275,68.105,232374239.0,Electoral Democracy,52.465,9.908864,47.535,Eastern and South-Eastern Asia
1376,Indonesia,IDN,2008,92.730000,-2.618162,4.133958,2.267637,6.695037,0.0,0.758190,...,35.2,Lower-middle income,7.917479,68.485,235469755.0,Electoral Democracy,51.665,11.295338,48.335,Eastern and South-Eastern Asia
1377,Indonesia,IDN,2009,93.550000,22.017902,7.862186,2.366299,4.027466,0.0,0.752215,...,35.1,Lower-middle income,6.920000,68.853,238620554.0,Electoral Democracy,50.866,6.688712,49.134,Eastern and South-Eastern Asia
1378,Indonesia,IDN,2010,94.150000,1.319571,11.459224,1.665478,4.195725,0.0,0.722585,...,36.4,Lower-middle income,10.920000,69.205,241834226.0,Electoral Democracy,50.086,7.070381,49.914,Eastern and South-Eastern Asia
1379,Indonesia,IDN,2011,94.830000,4.228906,11.522939,1.750454,4.968962,0.0,0.698343,...,39.7,Lower-middle income,12.280000,69.542,245115988.0,Electoral Democracy,49.405,8.397391,50.595,Eastern and South-Eastern Asia
1380,Indonesia,IDN,2012,96.000000,3.675770,11.329746,1.844120,3.709363,0.0,0.683597,...,39.7,Lower-middle income,14.520000,69.866,248451714.0,Electoral Democracy,48.724,6.048982,51.276,Eastern and South-Eastern Asia
1381,Indonesia,IDN,2013,96.464258,4.185756,11.232642,1.514861,3.308081,0.0,0.663068,...,40.0,Lower-middle income,14.940000,70.179,251805314.0,Electoral Democracy,48.045,5.518885,51.955,Eastern and South-Eastern Asia
1382,Indonesia,IDN,2014,97.010000,2.529367,11.101481,1.445983,2.773960,0.0,0.645515,...,39.4,Lower-middle income,17.140000,70.481,255128076.0,Electoral Democracy,47.365,4.765234,52.635,Eastern and South-Eastern Asia
1383,Indonesia,IDN,2015,97.537367,5.124025,11.798671,2.141863,1.650662,0.0,0.630847,...,39.7,Lower-middle income,22.062743,70.768,258383257.0,Electoral Democracy,46.687,3.116902,53.313,Eastern and South-Eastern Asia
1384,Indonesia,IDN,2016,97.620000,6.383631,13.691120,2.243018,1.383614,0.0,0.593157,...,38.6,Lower-middle income,25.447354,71.035,261556386.0,Electoral Democracy,46.011,2.626529,53.989,Eastern and South-Eastern Asia
1385,Indonesia,IDN,2017,98.140000,4.928758,14.720104,2.181155,1.686335,0.0,0.576168,...,38.1,Lower-middle income,32.335806,71.282,264650969.0,Electoral Democracy,45.341,3.096570,54.659,Eastern and South-Eastern Asia
1386,Indonesia,IDN,2018,98.510000,4.733578,15.333506,2.273700,2.521513,0.0,0.576168,...,37.8,Lower-middle income,39.904639,71.509,267670549.0,Electoral Democracy,44.675,4.463613,55.325,Eastern and South-Eastern Asia

###<b><span style='color:#55679C'>Quest C.4.2</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, tampilkan semua data yang Country Name-nya Indonesia namun hanya untuk tahun 2012 keatas saja</i>

In [19]:
# Answer C.4.2
data_Indonesia = data_world_sust.loc[(data_world_sust['Country Name'] == 'Indonesia') & (data_world_sust['Year'] >= 2012)]
display(data_Indonesia)

,Country Name,Country Code,Year,Access to electricity (% of population) - EG.ELC.ACCS.ZS,Adjusted net national income per capita (annual % growth) - NY.ADJ.NNTY.PC.KD.ZG,"Adjusted net savings, excluding particulate emission damage (% of GNI) - NY.ADJ.SVNX.GN.ZS",Adjusted savings: carbon dioxide damage (% of GNI) - NY.ADJ.DCO2.GN.ZS,Adjusted savings: natural resources depletion (% of GNI) - NY.ADJ.DRES.GN.ZS,Adjusted savings: net forest depletion (% of GNI) - NY.ADJ.DFOR.GN.ZS,Adjusted savings: particulate emission damage (% of GNI) - NY.ADJ.DPEM.GN.ZS,...,Gini index (World Bank estimate) - SI.POV.GINI,Income Classification (World Bank Definition),Individuals using the Internet (% of population) - IT.NET.USER.ZS,"Life expectancy at birth, total (years) - SP.DYN.LE00.IN","Population, total - SP.POP.TOTL",Regime Type (RoW Measure Definition),Rural population (% of total population) - SP.RUR.TOTL.ZS,Total natural resources rents (% of GDP) - NY.GDP.TOTL.RT.ZS,Urban population (% of total population) - SP.URB.TOTL.IN.ZS,World Regions (UN SDG Definition)
1380,Indonesia,IDN,2012,96.000000,3.675770,11.329746,1.844120,3.709363,0.0,0.683597,...,39.7,Lower-middle income,14.520000,69.866,248451714.0,Electoral Democracy,48.724,6.048982,51.276,Eastern and South-Eastern Asia
1381,Indonesia,IDN,2013,96.464258,4.185756,11.232642,1.514861,3.308081,0.0,0.663068,...,40.0,Lower-middle income,14.940000,70.179,251805314.0,Electoral Democracy,48.045,5.518885,51.955,Eastern and South-Eastern Asia
1382,Indonesia,IDN,2014,97.010000,2.529367,11.101481,1.445983,2.773960,0.0,0.645515,...,39.4,Lower-middle income,17.140000,70.481,255128076.0,Electoral Democracy,47.365,4.765234,52.635,Eastern and South-Eastern Asia
1383,Indonesia,IDN,2015,97.537367,5.124025,11.798671,2.141863,1.650662,0.0,0.630847,...,39.7,Lower-middle income,22.062743,70.768,258383257.0,Electoral Democracy,46.687,3.116902,53.313,Eastern and South-Eastern Asia
1384,Indonesia,IDN,2016,97.620000,6.383631,13.691120,2.243018,1.383614,0.0,0.593157,...,38.6,Lower-middle income,25.447354,71.035,261556386.0,Electoral Democracy,46.011,2.626529,53.989,Eastern and South-Eastern Asia
1385,Indonesia,IDN,2017,98.140000,4.928758,14.720104,2.181155,1.686335,0.0,0.576168,...,38.1,Lower-middle income,32.335806,71.282,264650969.0,Electoral Democracy,45.341,3.096570,54.659,Eastern and South-Eastern Asia
1386,Indonesia,IDN,2018,98.510000,4.733578,15.333506,2.273700,2.521513,0.0,0.576168,...,37.8,Lower-middle income,39.904639,71.509,267670549.0,Electoral Democracy,44.675,4.463613,55.325,Eastern and South-Eastern Asia

###<b><span style='color:#55679C'>Quest C.4.3</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, tampilkan kolom 'Country Name', 'GDP per capita (current US$) - NY.GDP.PCAP.CD', 'Inflation, consumer prices (annual %) - FP.CPI.TOTL.ZG' yang Country Name-nya Indonesia</i>

In [22]:
# Answer C.4.3
data_filter = data_world_sust.loc[
    data_world_sust['Country Name'] == 'Indonesia',
    ['Country Name', 'GDP per capita (current US$) - NY.GDP.PCAP.CD', 'Inflation, consumer prices (annual %) - FP.CPI.TOTL.ZG']
]

display(data_filter)

,Country Name,GDP per capita (current US$) - NY.GDP.PCAP.CD,"Inflation, consumer prices (annual %) - FP.CPI.TOTL.ZG"
1368,Indonesia,780.190205,3.688619
1369,Indonesia,748.257609,11.500115
1370,Indonesia,900.177588,11.900118
1371,Indonesia,1065.648520,6.757317
1372,Indonesia,1150.261367,6.064060
1373,Indonesia,1263.287332,10.453198
1374,Indonesia,1589.801489,13.108672
1375,Indonesia,1860.002811,6.406563
1376,Indonesia,2166.854231,10.226665
1377,Indonesia,2261.247309,4.386416
1378,Indonesia,3122.362673,5.134204
1379,Indonesia,3643.047176,5.356048
1380,Indonesia,3694.359340,4.279500
1381,Indonesia,3623.927241,6.412513
1382,Indonesia,3491.637491,6.394925
1383,Indonesia,3331.695115,6.363121
1384,Indonesia,3562.816334,3.525805
1385,Indonesia,3837.578024,3.808798
1386,Indonesia,3893.859578,3.198346

###<b><span style='color:#55679C'>Quest C.4.4</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, Pada tahun 2018, bandingkan GDP per capita pada negara Indonesia, Singapura, Malaysia dan Brunei Darussalam. Tampilkan kolom 'Country Name', 'Year', 'GDP per capita (current US$) - NY.GDP.PCAP.CD' saja </i>

In [23]:
# Answer C.4.4
filter_data = data_world_sust.loc[
    (data_world_sust['Year'] == 2018) &
    (data_world_sust['Country Name'].isin(['Indonesia', 'Singapore', 'Malaysia', 'Brunei Darussalam'])),
    ['Country Name', 'Year', 'GDP per capita (current US$) - NY.GDP.PCAP.CD']
]

display(filter_data)

           Country Name  Year  GDP per capita (current US$) - NY.GDP.PCAP.CD
474   Brunei Darussalam  2018                                   31628.476260
1386          Indonesia  2018                                    3893.859578
2184           Malaysia  2018                                   11377.654200
2659          Singapore  2018                                   66679.046490

## <b>C.5. <span style='color:#6A9AB0'>Sorting Row</span></b>

Menemukan data yang menarik dalam sebuah DataFrame seringkali lebih mudah jika dilakukan pengurutan baris datanya. Pengurutan dibagi menjadi dua yakni pengurutan secara `Ascending` (pengurutan naik A → Z) dan juga pengurutan secara `Descending` (pengurutan turun Z → A). Eksekusi sintaks berikut :

<p align="center"><code><b>DataFrame.sort_values(by, ascending=True, ignore_index=False)</b></code></p>

Jika ingin mengurutkan DataFrame pandas dengan memperhatikan argumen

<ul>
<li><b><i>by</i></b> sebagai satu atau lebih kolom yang ingin dijadikan patokan pengurutan</li>

<li><b><i>ascending</i></b> dapat diisikan True jika ingin terurut naik atau False jika ingin terurut turun (dafault : True)</li>

<li><b><i>ignore_index</i></b> dapat diisikan True jika ingin index masih terurut atau False jika indexnya masih dipertahankan sesuai data awal (dafault : False)</li>

</ul><br>

docs : <i>https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html</i>

###<b><span style='color:#55679C'>Quest C.5.1</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, tampilkan semua data yang Country Name-nya Indonesia namun urutkan dari GDP dari yang terbesar sampai yang terkecil</i>

In [29]:
# Answer C.5.1
pd.set_option('display.max_columns', None)

data_Indonesia = data_world_sust.loc[
    data_world_sust['Country Name'] == 'Indonesia'
    ].sort_values(by='GDP per capita (current US$) - NY.GDP.PCAP.CD', ascending=False)

display(data_Indonesia)

,Country Name,Country Code,Year,Access to electricity (% of population) - EG.ELC.ACCS.ZS,Adjusted net national income per capita (annual % growth) - NY.ADJ.NNTY.PC.KD.ZG,"Adjusted net savings, excluding particulate emission damage (% of GNI) - NY.ADJ.SVNX.GN.ZS",Adjusted savings: carbon dioxide damage (% of GNI) - NY.ADJ.DCO2.GN.ZS,Adjusted savings: natural resources depletion (% of GNI) - NY.ADJ.DRES.GN.ZS,Adjusted savings: net forest depletion (% of GNI) - NY.ADJ.DFOR.GN.ZS,Adjusted savings: particulate emission damage (% of GNI) - NY.ADJ.DPEM.GN.ZS,"Automated teller machines (ATMs) (per 100,000 adults) - FB.ATM.TOTL.P5",Broad money (% of GDP) - FM.LBL.BMNY.GD.ZS,Children out of school (% of primary school age) - SE.PRM.UNER.ZS,"Compulsory education, duration (years) - SE.COM.DURS","Cost of business start-up procedures, female (% of GNI per capita) - IC.REG.COST.PC.FE.ZS","Cost of business start-up procedures, male (% of GNI per capita) - IC.REG.COST.PC.MA.ZS",Exports of goods and services (% of GDP) - NE.EXP.GNFS.ZS,Final consumption expenditure (% of GDP) - NE.CON.TOTL.ZS,GDP (current US$) - NY.GDP.MKTP.CD,GDP per capita (current US$) - NY.GDP.PCAP.CD,General government final consumption expenditure (% of GDP) - NE.CON.GOVT.ZS,Gross national expenditure (% of GDP) - NE.DAB.TOTL.ZS,Gross savings (% of GDP) - NY.GNS.ICTR.ZS,Imports of goods and services (% of GDP) - NE.IMP.GNFS.ZS,"Inflation, consumer prices (annual %) - FP.CPI.TOTL.ZG","Primary completion rate, total (% of relevant age group) - SE.PRM.CMPT.ZS",Proportion of seats held by women in national parliaments (%) - SG.GEN.PARL.ZS,"Pupil-teacher ratio, primary - SE.PRM.ENRL.TC.ZS",Renewable electricity output (% of total electricity output) - EG.ELC.RNEW.ZS,Renewable energy consumption (% of total final energy consumption) - EG.FEC.RNEW.ZS,"School enrollment, preprimary (% gross) - SE.PRE.ENRR","School enrollment, primary (% gross) - SE.PRM.ENRR","School enrollment, secondary (% gross) - SE.SEC.ENRR",Trade (% of GDP) - NE.TRD.GNFS.ZS,Women Business and the Law Index Score (scale 1-100) - SG.LAW.INDX,Prevalence of undernourishment (%) - SN_ITK_DEFC - 2.1.1,Proportion of population below international poverty line (%) - SI_POV_DAY1 - 1.1.1,Proportion of population covered by at least a 2G mobile network (%) - IT_MOB_2GNTWK - 9.c.1,Proportion of population covered by at least a 3G mobile network (%) - IT_MOB_3GNTWK - 9.c.1,Proportion of population using basic drinking water services (%) - SP_ACS_BSRVH2O - 1.4.1,"Unemployment rate, male (%) - SL_TLF_UEM - 8.5.2","Unemployment rate, women (%) - SL_TLF_UEM - 8.5.2","Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes",Continent,Gini index (World Bank estimate) - SI.POV.GINI,Income Classification (World Bank Definition),Individuals using the Internet (% of population) - IT.NET.USER.ZS,"Life expectancy at birth, total (years) - SP.DYN.LE00.IN","Population, total - SP.POP.TOTL",Regime Type (RoW Measure Definition),Rural population (% of total population) - SP.RUR.TOTL.ZS,Total natural resources rents (% of GDP) - NY.GDP.TOTL.RT.ZS,Urban population (% of total population) - SP.URB.TOTL.IN.ZS,World Regions (UN SDG Definition)
1386,Indonesia,IDN,2018,98.510000,4.733578,15.333506,2.273700,2.521513,0.0,0.576168,54.374648,38.817581,5.62332,9.0,6.1,6.1,21.002747,66.001127,1.042270e+12,3893.859578,9.021232,100.571713,31.680523,22.071562,3.198346,102.334839,19.821429,17.03493,17.037001,20.863899,62.343658,106.410820,88.910172,43.074309,64.375,6.4,3.6,98.71,97.70,91.0,4.5,4.2,576.584,Asia,37.8,Lower-middle income,39.904639,71.509,267670549.0,Electoral Democracy,44.675,4.463613,55.325,Eastern and South-Eastern Asia
1385,Indonesia,IDN,2017,98.140000,4.928758,14.720104,2.181155,1.686335,0.0,0.576168,55.140507,39.876634,5.06120,9.0,11.0,11.0,20.177304,66.396144,1.015620e+12,3837.578024,9.120571,100.106739,30.878363,19.178193,3.808798,100.825920,19.821429,16.06371,12.560554,25.432800,63.193069,105.911430,87.059219,39.355497,64.375,6.4,4.5,98.60,93.78,90.0,4.1,3.6,531.012,Asia,38.1,Lower-middle income,32.335806,71.282,264650969.0,Electoral Democracy,45.341,3.096570,54.659,Eastern and South-Eastern Asia
1380,Indonesia,IDN,2012,96.000000,3.675770,11.329746,1.844120,3.709363,0.0,0.683597,35.729558,38.389288,4.05297,9.0,NaN,NaN,24.594379,65.638035,9.178700e+11,3694.359340,9.248788,100.709628,31.985370,24.988520,4.279500,103.098259,18.571429,18.59225,11.236814,28.784800,50.009789,109.273422,80.452332,49.582898,64.375,9.4,9.5,NaN,NaN,NaN,NaN,NaN,526.383,Asia,39.7,Lower-middle income,14.520000,69.866,248451714.0,Electoral Democracy,48.724,6.048982,51.276,Eastern and South-Eastern Asia
1379,Indonesia,IDN,2011,94.830000,4.228906,11.522939,1.750454,4.968962,0.0,0.698343,16.448188,36.738002,3.16939,9.0,NaN,NaN,26.327353,64.482034,8.929690e+11,3643.047176,9.058677,97.466367,33.220073,23.852660,5.356048,NaN,18.214286,18.98040,11.992891,30.919001,43.088009,109.179833,79.114479,50.180013,64.375,10.7,10.9,100.00,NaN,NaN,NaN,NaN,508.073,Asia,39.7,Lower-middle income,12.280000,69.542,245115988.0,Electoral Democracy,49.405,8.397391,50.595,Eastern and South-Eastern Asia
1381,Indonesia,IDN,2013,96.464258,4.185756,11.232642,1.514861,3.308081,0.0,0.663068,42.016621,39.075474,6.27357,9.0,22.0,22.0,23.923576,66.347182,9.125240e+11,3623.927241,9.517720,100.178539,31.121767,24.713796,6.412513,101.145630,18.571429,16.09408,12.270160,29.702499,54.346619,106.841591,82.637642,48.637373,64.375,8.3,7.3,NaN,NaN,NaN,NaN,NaN,411.191,Asia,40.0,Lower-middle income,14.940000,70.179,251805314.0,Electoral Democracy,48.045,5.518885,51.955,Eastern and South-Eastern Asia
1384,Indonesia,IDN,2016,97.620000,6.383631,13.691120,2.243018,1.383614,0.0,0.593157,54.337374,40.357090,6.37853,9.0,19.4,19.4,19.088994,67.354611,9.318770e+11,3562.816334,9.527810,101.213350,29.922768,18.332348,3.525805,NaN,17.117117,13.97814,12.071958,27.834801,61.876438,105.609878,84.952118,37.421342,64.375,6.8,5.2,87.90,74.86,89.0,4.6,3.9,568.194,Asia,38.6,Lower-middle income,25.447354,71.035,261556386.0,Electoral Democracy,46.011,2.626529,53.989,Eastern and South-Eastern Asia
1382,Indonesia,IDN,2014,97.010000,2.529367,11.101481,1.445983,2.773960,0.0,0.645515,49.205442,39.483850,6.82466,9.0,21.2,21.2,23.665985,66.564142,8.908150e+11,3491.637491,9.425026,101.164486,30.668909,24.414191,6.394925,103.451531,16.936937,16.55935,11.475100,28.318899,57.875290,106.073402,82.682381,48.080176,64.375,7.7,6.2,NaN,60.00,88.0,4.2,3.9,416.823,Asia,39.4,Lower-middle income,17.140000,70.481,255128076.0,Electoral Democracy,47.365,4.765234,52.635,Eastern and South-Eastern Asia
1383,Indonesia,IDN,2015,97.537367,5.124025,11.798671,2.141863,1.650662,0.0,0.630847,52.965375,39.464420,NaN,9.0,20.0,20.0,21.160179,67.199432,8.608540e+11,3331.695115,9.749414,101.262224,30.123356,20.777461,6.363121,NaN,17.117117,NaN,10.651156,26.951900,NaN,105.960243,86.122749,41.937640,64.375,7.0,5.8,87.90,60.00,89.0,4.6,4.4,507.012,Asia,39.7,Lower-middle income,22.062743,70.768,258383257.0,Electoral Democracy,46.687,3.116902,53.313,Eastern and South-Eastern Asia
1378,Indonesia,IDN,2010,94.150000,1.319571,11.459224,1.665478,4.195725,0.0,0.722585,13.039890,36.001718,2.74617,9.0,NaN,NaN,24.299031,65.223091,7.550940e+11,3122.362673,9.005915,98.103212,32.727423,22.402243,5.134204,100.589088,18.035714,19.01170,15.854025,34.811298,41.442768,109.150337,76.426247,46.701274,64.375,13.0,13.3,NaN,NaN,NaN,NaN,NaN,428.174,Asia,36.4,Lower-middle income,10.920000,69.205,241834226.0,Electoral Democracy,50.086,7.070381,49.914,Eastern and South-Eastern Asia
1377,Indonesia,IDN,2009,93.550000,22.017902,7.862186,2.366299,4.027466,0.0,0.752215,14.115549,38.196684,3.16278,9.0,NaN,NaN,24.159120,68.291934,5.395800e+11,2261.247309,9.589178,99.277127,29.056377,21.353002,4.386416,98.549088,17.857143,19.77613,13.233062,38.179298,45.498489,108.549240,74.627647,45.512121,64.375,15.5,15.5,NaN,NaN,NaN,NaN,NaN,447.099,Asia,35.1,Lower-middle income,6.920000,68.853,238620554.0,Electoral Democracy,50.866,6.688712,49.134,Eastern and South-Eastern Asia
1376,Indonesia,IDN,2008,92.730000,-2.618162,4.133958,2.267637,6.695037,0.0,0.758190,13.114784,38.309921,3.90732,9.0,NaN,NaN,29.808284,69.045034,5.102290e+11,2166.854231,8.423781,96.861278,28.452413,28.753115,10.226665,96.692596,11.636364,20.68852,13.315832,41.122101,43.466400,107.822540,69.656227,58.561400,64.375,17.4,19.0,NaN,NaN,NaN,NaN,NaN,417.562,Asia,35.2,Lower-middle income,7.917479,68.485,235469755.0,Electoral Democracy,51.665,11.295338,48.335,Eastern and South-Eastern Asia
1375,Indonesia,IDN,2007,91.100000,-645.655290,1.211209,2.328722,6.306531,0.0,0.776428,11.464783,41.754148,3.04320,9.0,NaN,NaN,29.435718,71.889159,4.322170e+11,1860.002811,8.346470,96.809443,25.179123,25.393531,6.406563,96.645813,11.636364,18.81593,12.903884,40.013802,40.884399,109.305771,70.540916,54.829250,64.375,18.5,19.3,NaN,NaN,NaN,NaN,NaN,376.865,Asia,35.7,Lower-middle income,5.786275,68.105,232374239.0,Electoral Democracy,52.465,9.908864,47.535,Eastern and South-Eastern Asia
1374,Indonesia,IDN,2006,90.620000,-52.439762,1.621539,2.420132,6.223231,0.0,0.787130,10.493692,41.401723,5.40089,9.0,NaN,NaN,31.034716,71.296226,3.645710e+11,1589.801489,8.627169,96.696443,25.777144,25.622411,13.108672,92.560898,11.272727,19.00007,12.258777,40.065399,34.666351,106.268379,62.641029,56.657127,64.375,19.0,23.9,90.00,NaN,NaN,NaN,NaN,346.443,Asia,34.3,Lower-middle income,4.764813,67.717,229318262.0,Electoral Democracy,53.262,9.291362,46.738,Eastern and South-Eastern Asia
1373,Indonesia,IDN,2005,85.421112,229.493078,-1.136493,2.921757,6.790490,0.0,0.798981,9.321786,43.354015,6.74832,9.0,NaN,NaN,34.067268,72.471998,2.858690e+11,1263.287332,8.109508,97.553408,24.338487,29.920668,10.453198,94.273438,11.272727,20.41336,13.605533,41.573200,31.538960,107.955437,60.154289,63.987936,64.375,19.2,18.0,90.00,NaN,NaN,NaN,NaN,343.336,Asia,33.0,Lower-middle income,3.602025,67.334,226289468.0,Electoral Democracy,54.058,9.731952,45.942,Eastern and South-Eastern Asia
1372,Indonesia,IDN,2004,89.010000,-88.418979,-3.832204,3.036238,5.428775,0.0,0.819240,8.560131,45.032885,5.79870,9.0,NaN,NaN,32.216695,75.090350,2.568370e+11,1150.261367,8.321868,99.146716,20.764290,27.544600,6.064060,95.595703,11.272727,20.12598,13.606518,41.455101,27.019991,108.934303,61.867241,59.761295,61.875,19.1,21.0,90.00,NaN,NaN,NaN,NaN,339.848,Asia,32.7,Lower-middle income,2.600286,66.969,223285666.0,Electoral Democracy,54.851,8.366587,45.149,Eastern and South-Eastern Asia
1371,Indonesia,IDN,2003,87.940000,-446.094475,-2.707184,2.945079,4.143268,0.0,0.823148,NaN,47.041345,5.04850,9.0,NaN,NaN,30.477655,76.267506,2.347720e+11,1065.648520,8.129486,101.866005,20.684050,23.138839,6.757317,95.659241,8.000000,20.29418,13.638536,43.000000,25.727921,109.526527,60.143219,53.616494,59.375,18.9,19.3,NaN,NaN,NaN,NaN,NaN,316.655,Asia,31.9,Lower-middle income,2.387020,66.631,220309473.0,Electoral Democracy,55.644,6.354044,44.356,Eastern and South-Eastern Asia
1370,Indonesia,IDN,2002,87.600000,-128.869275,-1.002698,3.256460,4.368919,0.0,0.836755,NaN,48.171162,4.54313,9.0,NaN,NaN,32.687621,74.879695,1.956610e+11,900.177588,7.257458,96.283766,23.017408,26.391841,11.900118,95.054024,8.000000,20.90186,14.953288,44.657600,24.404490,109.920952,57.161591,59.079462,50.000,19.1,19.0,NaN,NaN,NaN,NaN,NaN,307.361,Asia,31.7,Low income,2.134136,66.321,217357790.0,Electoral Democracy,56.432,6.475675,43.568,Eastern and South-Eastern Asia
1368,Indonesia,IDN,2000,86.300000,175.094481,13.605523,3.174163,7.519280,0.0,0.995095,NaN,53.882681,NaN,NaN,NaN,NaN,40.977308,68.182366,1.650210e+11,780.190205,6.531995,90.428063,26.286899,30.459567,3.688619,NaN,8.000000,22.11772,15.956068,45.624699,24.105989,108.759491,55.077122,71.436876,50.000,NaN,34.9,89.00,NaN,NaN,NaN,NaN,265.803,Asia,28.6,Low income,NaN,NaN,NaN,Electoral Democracy,57.998,NaN,NaN,Eastern and South-Eastern Asia
1369,Indonesia,IDN,2001,86.260000,29.740863,1.569265,3.703188,5.594517,0.0,0.900631,NaN,50.885519,3.84774,NaN,NaN,NaN,39.032139,70.039221,1.604470e+11,748.257609,6.889059,92.578487,27.199794,30.761068,11.500115,93.756271,8.000000,22.24524,17.474865,44.328999,24.449711,109.750923,55.540360,69.793208,50.000,19.2,31.2,NaN,NaN,NaN,NaN,NaN,297.530,Asia,29.0,Low income,2.018614,66.037,214427419.0,Electoral Democracy,57.217,8.147302,42.783,Eastern and South-Eastern Asia

###<b><span style='color:#55679C'>Quest C.5.2</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, pada tahun 2018, negara mana saja yang GDPnya masuk kedalam 10 terbaik? Tampilkan hanya kolom 'Country Name', 'Year', 'GDP per capita (current US$) - NY.GDP.PCAP.CD'  </i>

In [30]:
# Answer C.5.2
top_10_GDP = data_world_sust.loc[
    data_world_sust['Year'] == 2018
].sort_values(
    by='GDP per capita (current US$) - NY.GDP.PCAP.CD',
    ascending=False
).head(10)[['Country Name', 'Year', 'GDP per capita (current US$) - NY.GDP.PCAP.CD']]

display(top_10_GDP)

          Country Name  Year  GDP per capita (current US$) - NY.GDP.PCAP.CD
1842        Luxembourg  2018                                   116597.29560
1880  Macao SAR, China  2018                                    87554.71386
569        Switzerland  2018                                    86429.50082
2298            Norway  2018                                    82267.80932
1424           Ireland  2018                                    79297.72920
1481           Iceland  2018                                    74348.36228
2659         Singapore  2018                                    66679.04649
2545             Qatar  2018                                    65907.94843
3134     United States  2018                                    63064.41841
873            Denmark  2018                                    61598.53670

###<b><span style='color:#55679C'>Quest C.5.3</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, pada tahun 2016, negara mana saja yang Emisi karbon dioksida (CO2) berbasis produksi tahunannya masuk dalam 5 negara penghasil emisi CO2 terkecil? Tampilkan nama negara, tahun dan jumlah emisi karbonnya! </i>

In [33]:
# Answer C.5.3
smallest_emitters_2016_top5 = data_world_sust.loc[
    data_world_sust['Year'] == 2016
].sort_values(
    by='Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes', ascending=True
).head(5)[
    ['Country Name', 'Year', 'Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes']
]

display(smallest_emitters_2016_top10)

,Country Name,Year,"Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes"
2980,Tonga,2016,0.128
3227,Vanuatu,2016,0.147
852,Dominica,2016,0.180
719,Comoros,2016,0.202
3170,St. Vincent and the Grenadines,2016,0.253
2676,Solomon Islands,2016,0.289
1194,Guinea-Bissau,2016,0.293
529,Central African Republic,2016,0.297
1764,St. Lucia,2016,0.333
206,Burundi,2016,0.443

###<b><span style='color:#55679C'>Quest C.5.4</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, pada tahun 2018 di benua Asia, tampilkan 10 negara dengan produksi Emisi CO2 terbesar. Urutkan dari yang terbesar hingga terkecil</i>

In [34]:
# Answer C.5.4
df = data_world_sust.loc[
    (data_world_sust['Year'] == 2018) & (data_world_sust['Continent'] == 'Asia')
].sort_values(
    by='Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes',
    ascending = False
).head(10)[['Country Name', 'Year', 'Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes']]

display(df)

,Country Name,Year,"Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes"
607,China,2018,9956.569
1405,India,2018,2591.324
1576,Japan,2018,1135.688
1443,"Iran, Islamic Rep.",2018,755.402
1671,"Korea, Rep.",2018,634.934
2621,Saudi Arabia,2018,576.758
1386,Indonesia,2018,576.584
3039,Turkey,2018,419.195
1595,Kazakhstan,2018,319.647
2925,Thailand,2018,292.453

## <b>C.6. <span style='color:#6A9AB0'>Summarize Data</span></b>

Di pandas, method `DataFrame.describe()` digunakan untuk menghasilkan statistik deskriptif dari DataFrame. Metode ini sangat berguna untuk dengan cepat memahami statistik dasar dari data. Berikut adalah statistik utama yang disediakan :

* `Jumlah` : Jumlah nilai non-null dalam setiap kolom.
* `Rata-rata` : Rata-rata aritmetika dari setiap kolom.
* `Standar Deviasi` : Ukuran dispersi nilai-nilai sekitar rata-rata.
* `Minimum` : Nilai minimum dalam setiap kolom.
* `Kuartil 25 (Q1)` : Nilai di bawahnya 25% data berada.
* `Kuartil 50 (Median atau Q2)` : Nilai di bawahnya 50% data berada (yaitu nilai tengah).
* `Kuartil 75 (Q3)` : Nilai di bawahnya 75% data berada.
* `Maksimum` : Nilai maksimum dalam setiap kolom.

###<b><span style='color:#55679C'>Quest C.6</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, hitung semua statistik deskriptif menggunakan .describe() pada kolom numerik!</i>

In [61]:
# Answer C.6
data_world_sust.describe()

,Year,Access to electricity (% of population) - EG.ELC.ACCS.ZS,Adjusted net national income per capita (annual % growth) - NY.ADJ.NNTY.PC.KD.ZG,"Adjusted net savings, excluding particulate emission damage (% of GNI) - NY.ADJ.SVNX.GN.ZS",Adjusted savings: carbon dioxide damage (% of GNI) - NY.ADJ.DCO2.GN.ZS,Adjusted savings: natural resources depletion (% of GNI) - NY.ADJ.DRES.GN.ZS,Adjusted savings: net forest depletion (% of GNI) - NY.ADJ.DFOR.GN.ZS,Adjusted savings: particulate emission damage (% of GNI) - NY.ADJ.DPEM.GN.ZS,"Automated teller machines (ATMs) (per 100,000 adults) - FB.ATM.TOTL.P5",Broad money (% of GDP) - FM.LBL.BMNY.GD.ZS,...,"Unemployment rate, male (%) - SL_TLF_UEM - 8.5.2","Unemployment rate, women (%) - SL_TLF_UEM - 8.5.2","Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes",Gini index (World Bank estimate) - SI.POV.GINI,Individuals using the Internet (% of population) - IT.NET.USER.ZS,"Life expectancy at birth, total (years) - SP.DYN.LE00.IN","Population, total - SP.POP.TOTL",Rural population (% of total population) - SP.RUR.TOTL.ZS,Total natural resources rents (% of GDP) - NY.GDP.TOTL.RT.ZS,Urban population (% of total population) - SP.URB.TOTL.IN.ZS
count,3287.000000,3193.000000,2566.000000,2628.000000,3220.000000,3094.000000,3111.000000,3099.000000,2285.000000,2777.000000,...,1807.000000,1806.000000,3285.000000,1303.000000,2986.000000,3096.000000,3.106000e+03,3278.000000,3053.000000,3106.000000
mean,2009.000000,79.300662,2.499857,8.870028,1.742674,3.812051,0.692833,0.880541,45.391741,57.034297,...,7.987327,9.810687,174.646907,37.512203,33.117667,70.160098,3.891506e+07,42.890186,7.015880,57.264100
std,5.478059,30.398748,18.752649,12.277347,1.957442,6.958003,2.657800,1.084312,45.915444,43.806176,...,5.781539,7.159265,757.653194,8.595502,29.386654,9.205632,1.413757e+08,22.705962,10.730922,22.687638
min,2000.000000,1.270180,-645.655290,-97.524776,0.090292,0.000000,0.000000,0.009500,0.000000,2.857408,...,0.100000,0.200000,0.048000,23.700000,0.000000,40.369000,6.967100e+04,0.000000,0.000000,8.461000
25%,2004.000000,62.900000,-0.246761,3.339159,0.741310,0.078542,0.000000,0.149597,9.558670,27.222821,...,4.100000,4.725000,2.426000,30.900000,6.000000,65.109000,2.406866e+06,24.816500,0.385851,39.546750
50%,2009.000000,98.653969,2.545392,8.752619,1.145867,0.878741,0.000000,0.388686,34.951665,47.054379,...,6.400000,7.500000,12.621000,35.600000,25.000000,72.564634,8.368371e+06,42.648000,2.122046,57.450000
75%,2014.000000,100.000000,5.545831,15.290790,2.056927,4.656705,0.097040,1.286091,62.252217,72.465711,...,10.000000,12.800000,72.012000,42.800000,58.000000,76.572750,2.605396e+07,60.732750,8.878282,75.372500
max,2018.000000,100.000000,229.493078,45.354086,27.101473,71.290764,40.772569,6.542877,324.172288,396.185604,...,37.000000,42.800000,9956.569000,64.800000,99.652849,84.934146,1.392730e+09,91.754000,81.949962,100.000000

## <b>C.7. <span style='color:#6A9AB0'>Aggregation</span></b>

Agregasi data merupakan serangkaian proses yang dilakukan untuk melakukan pengumpulan data dan dinyatakan dalam bentuk ringkasan sebagai contoh menghitung total yang dikelompokkan berdasarkan kategori tertentu, dsb.

Untuk melakukan agregasi gunakan sintaks berikut

<p align="center"><code><b>DataFrame.group_by(by, as_index).agg(kolom_hasil_aggregasi = (kolom_dihitung, jenis_agregasi))</b></code></p>

Jenis agregasi :
* sum = Menghitung total data
* mean = Menghitung rataan data
* max = Menghitung nilai maksimum data
* min = Menghitung nilai minimum data
* nunique = Menghitung jumlah data unik data
* count = Menghitung banyak data

###<b><span style='color:#55679C'>Quest C.7.1</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, hitung rata-rata GDP tiap Benua pada seluruh tahun!</i>

In [28]:
# Answer C.4.1
mean_GDP = data_world_sust.groupby('Continent').agg(mean_GDP = ('GDP per capita (current US$) - NY.GDP.PCAP.CD', 'mean'))
display(mean_GDP)

                   mean_GDP
Continent
Africa          2190.614397
Asia           11860.569243
Europe         26220.479103
North America  11943.223415
Oceania        14645.038023
South America   6368.159148

###<b><span style='color:#55679C'>Quest C.7.2</span></b>

<i>Pada DataFrame <code>data_world_sust</code>, dengan cara agregasi buatkan 2 insight lainnya yang menurut kamu perlu dianalisa sertakan juga insight yang kamu peroleh!</i>

In [35]:
# Answer C.7.2.1
# Menghitung rata-rata Penggunaan Energi Terbarukan per Benua
average_renewable_energy_per_continent = data_world_sust.groupby('Continent', as_index=False).agg(
    rata_rata_penggunaan_energi_terbarukan=('Renewable energy consumption (% of total final energy consumption) - EG.FEC.RNEW.ZS', 'mean')
)

# Menampilkan hasil dengan format yang mudah dipahami
display(average_renewable_energy_per_continent)

       Continent  rata_rata_penggunaan_energi_terbarukan
0         Africa                               61.446756
1           Asia                               21.308767
2         Europe                               18.771750
3  North America                               23.068256
4        Oceania                               28.269439
5  South America                               29.872472

In [37]:
# Answer C.7.2.2
# Menghitung rata-rata Pengeluaran Pemerintah untuk Konsumsi Akhir per Benua
average_gov_exp_per_continent = data_world_sust.groupby('Continent', as_index=False).agg(
    rata_rata_pengeluaran_pemerintah=('General government final consumption expenditure (% of GDP) - NE.CON.GOVT.ZS', 'mean')
)

# Menampilkan hasil
display(average_gov_exp_per_continent)

       Continent  rata_rata_pengeluaran_pemerintah
0         Africa                         15.018418
1           Asia                         15.421302
2         Europe                         19.287896
3  North America                         15.308493
4        Oceania                         18.516184
5  South America                         13.799687

---

<br>
<a href="https://www.linkedin.com/in/melati-anggiasari/"><img src="https://img.shields.io/badge/-© 2024 Melati Anggiasari-417DAC?style=for-the-badge&logoColor=white"/></a>